#SID
SID = AKfycbzD2Pv7O_-43yEe0aM0V0ihVws5SfDy5LX-tzrXr_YOPGejnxwLfqFAGm2vHH2H9zLnag

download:	
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=correspondence" -O correspondence.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=sender_recipient" -O sender_recipient.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=decade" -O decade.json
		