#SID
SID = AKfycbwzEiJiBoPElwEkW0bjSa2M7uqLoOinvuCeuJZXbzyeryqYOFRDymlv2dMFyA9m1XIWHA

download:	
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=correspondence" -O correspondence.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=sender_recipient" -O sender_recipient.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=decade" -O decade.json
		